[package]
name = "string_interner"
version = "0.1.0"
edition = "2021"

[[bench]]
name = "intern"
harness = false

[dependencies]
fxhash = "0.2.1"

[dev-dependencies]
criterion = "0.5.1"
codspeed-criterion-compat = "2.3.3"
rand_core = "0.6.4"
rand_xorshift = "0.3.0"
