name: benchmark

on:
  push:
    branches:
      - "main"
  pull_request:
  workflow_dispatch:

jobs:
  benchmark:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup rust toolchain, cache and cargo-codspeed binary
        uses: moonrepo/setup-rust@v1
        with:
          cache-base: main
          cache-target: release
          bins: cargo-codspeed

      - name: Build the benchmark target(s)
        run: cargo codspeed build
        env:
          RUSTFLAGS: "-C debuginfo=2 -C strip=none"

      - name: Run the benchmarks
        uses: CodSpeedHQ/action@v2
        timeout-minutes: 30
        with:
          run: cargo codspeed run
          token: ${{ secrets.CODSPEED_TOKEN }}
